/**
 * @file MainPage.xaml.h
 * @brief Main Page Header for WinRT Frontend
 * 
 * This file declares the MainPage class that corresponds to MainPage.xaml.
 * In a full WinRT project, this would be partially generated by the XAML compiler.
 * 
 * SPDX-License-Identifier: GPL-3.0-or-later
 * SPDX-FileCopyrightText: Copyright (C) 2024 LibreVMM Contributors
 */

#ifndef MAINPAGE_XAML_H
#define MAINPAGE_XAML_H

#include "pch.h"

// Forward declare the ref class
namespace LibreVMM { namespace WinRT {
    ref class MainPage;
}}

namespace LibreVMM { namespace WinRT {

/**
 * @brief Main Page for WinRT Frontend
 * 
 * Implements basic VM management UI for UWP / Windows Mobile.
 * Uses the IVBoxFrontend API for all VM operations.
 */
[Windows::UI::Xaml::Data::Bindable]
public ref class MainPage sealed : public Windows::UI::Xaml::Controls::Page
{
public:
    /// @brief Constructor
    MainPage();

    /// @brief Page loaded event handler
    void Page_Loaded(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ e);

    // Event handlers
    void RefreshButton_Click(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ e);
    void NewVMButton_Click(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ e);
    void StartButton_Click(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ e);
    void PauseButton_Click(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ e);
    void StopButton_Click(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ e);
    void SettingsButton_Click(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ e);
    void TakeSnapshotButton_Click(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ e);
    void VMListView_SelectionChanged(Platform::Object^ sender, Windows::UI::Xaml::Controls::SelectionChangedEventArgs^ e);

private:
    // Private helper methods
    void RefreshVMList();
    void UpdateActionButtons(Platform::String^ state);
    
    // UI Element references (these correspond to x:Name attributes in XAML)
    Windows::UI::Xaml::Controls::ListView^ VMListView;
    Windows::UI::Xaml::Controls::ListView^ SnapshotsListView;
    Windows::UI::Xaml::Controls::Button^ RefreshButton;
    Windows::UI::Xaml::Controls::Button^ NewVMButton;
    Windows::UI::Xaml::Controls::Button^ StartButton;
    Windows::UI::Xaml::Controls::Button^ PauseButton;
    Windows::UI::Xaml::Controls::Button^ StopButton;
    Windows::UI::Xaml::Controls::Button^ SettingsButton;
    Windows::UI::Xaml::Controls::Button^ TakeSnapshotButton;
    Windows::UI::Xaml::Controls::StackPanel^ DetailsPanel;
    Windows::UI::Xaml::Controls::TextBlock^ VMNameText;
    Windows::UI::Xaml::Controls::TextBlock^ VMStateText;
    Windows::UI::Xaml::Controls::TextBlock^ OSTypeText;
    Windows::UI::Xaml::Controls::TextBlock^ MemoryText;
    Windows::UI::Xaml::Controls::TextBlock^ CPUCountText;
    Windows::UI::Xaml::Controls::TextBlock^ VRAMText;
    Windows::UI::Xaml::Controls::TextBlock^ StatusText;
    Windows::UI::Xaml::Controls::TextBlock^ VMCountText;
    Windows::UI::Xaml::Shapes::Ellipse^ StatusIndicator;
    
    // Frontend reference
    std::unique_ptr<IVBoxFrontend> m_frontend;
    
    // InitializeComponent - in a real WinRT app this is generated
    void InitializeComponent();
};

} } // namespace LibreVMM::WinRT

#endif // MAINPAGE_XAML_H
